"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { CalendarBlank, Camera, CaretRight, Check, CheckCircle, ClipboardText, ClockCountdown, Engine, Plus, Sparkle, Toolbox, WarningCircle, Wrench } from "@phosphor-icons/react";

type JobStatus="Scheduled"|"In progress"|"Completed"|"Overdue";
type Equipment={id:number;name:string;code:string;location:string;type:string;interval:number;lastService:string;nextService:string;health:"Good"|"Attention"|"Critical"};
type Job={id:number;equipmentId:number;title:string;due:string;assignee:string;status:JobStatus;checklist:{label:string;done:boolean}[];faults:string;parts:string;beforePhoto?:string;afterPhoto?:string;report?:string};

const equipmentSeed:Equipment[]=[
  {id:11,name:"Máy phát điện chính",code:"GEN-01",location:"Phòng kỹ thuật B1",type:"Generator",interval:30,lastService:"2026-08-12",nextService:"2026-09-12",health:"Attention"},
  {id:12,name:"Tủ điện phân phối",code:"MDB-02",location:"Nhà xưởng A",type:"Electrical",interval:90,lastService:"2026-07-20",nextService:"2026-10-18",health:"Good"},
  {id:13,name:"Hệ thống HVAC",code:"HVAC-04",location:"Văn phòng tầng 4",type:"HVAC",interval:60,lastService:"2026-07-04",nextService:"2026-09-02",health:"Critical"},
  {id:14,name:"Bơm nước tuần hoàn",code:"PMP-08",location:"Khu utility",type:"Pump",interval:45,lastService:"2026-08-22",nextService:"2026-10-06",health:"Good"}
];
const jobsSeed:Job[]=[
  {id:501,equipmentId:13,title:"Bảo trì định kỳ HVAC",due:"2026-09-02",assignee:"Đức Huy",status:"Overdue",checklist:[{label:"Ngắt nguồn và LOTO",done:true},{label:"Vệ sinh lưới lọc",done:true},{label:"Đo dòng vận hành",done:false},{label:"Kiểm tra rò rỉ gas",done:false}],faults:"Độ rung quạt cao hơn bình thường",parts:"",},
  {id:502,equipmentId:11,title:"Kiểm tra máy phát điện",due:"2026-09-16",assignee:"Thiện Phong",status:"In progress",checklist:[{label:"Kiểm tra dầu máy",done:true},{label:"Kiểm tra nước làm mát",done:true},{label:"Chạy thử có tải",done:false}],faults:"",parts:"Lọc dầu GEN-F12"},
  {id:503,equipmentId:14,title:"Bảo dưỡng bơm tuần hoàn",due:"2026-10-06",assignee:"Khánh Linh",status:"Scheduled",checklist:[{label:"Kiểm tra phớt bơm",done:false},{label:"Đo độ rung",done:false},{label:"Bôi trơn vòng bi",done:false}],faults:"",parts:""},
  {id:504,equipmentId:12,title:"Kiểm tra tủ MDB",due:"2026-08-20",assignee:"Thiện Phong",status:"Completed",checklist:[{label:"Siết đầu cos",done:true},{label:"Chụp ảnh nhiệt",done:true},{label:"Vệ sinh tủ",done:true}],faults:"Không phát hiện",parts:"Không"}
];

function load<T>(key:string,fallback:T):T{if(typeof window==="undefined")return fallback;try{return JSON.parse(localStorage.getItem(key)||"") as T}catch{return fallback}}
function daysUntil(date:string){return Math.ceil((new Date(date).getTime()-new Date("2026-09-15").getTime())/86400000)}

export default function MaintenanceManager(){
  const [ready,setReady]=useState(false);const [active,setActive]=useState("dashboard");const [equipment,setEquipment]=useState<Equipment[]>(equipmentSeed);const [jobs,setJobs]=useState<Job[]>(jobsSeed);const [selected,setSelected]=useState<Job|null>(null);const [createJob,setCreateJob]=useState(false);const [createEquipment,setCreateEquipment]=useState(false);const [toast,setToast]=useState("");
  useEffect(()=>{setEquipment(load("upkeep-equipment",equipmentSeed));setJobs(load("upkeep-jobs",jobsSeed));setReady(true)},[]);
  useEffect(()=>{if(ready)localStorage.setItem("upkeep-equipment",JSON.stringify(equipment))},[equipment,ready]);useEffect(()=>{if(ready)localStorage.setItem("upkeep-jobs",JSON.stringify(jobs))},[jobs,ready]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),2600);return()=>clearTimeout(t)},[toast]);
  const stats=useMemo(()=>({due:jobs.filter(j=>j.status==="Scheduled"&&daysUntil(j.due)<=14).length,progress:jobs.filter(j=>j.status==="In progress").length,done:jobs.filter(j=>j.status==="Completed").length,overdue:jobs.filter(j=>j.status==="Overdue").length}),[jobs]);
  function addEquipment(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const item:Equipment={id:Math.max(...equipment.map(x=>x.id))+1,name:String(f.get("name")),code:String(f.get("code")),location:String(f.get("location")),type:String(f.get("type")),interval:Number(f.get("interval")),lastService:String(f.get("lastService")),nextService:String(f.get("nextService")),health:"Good"};setEquipment([item,...equipment]);setCreateEquipment(false);setToast("Đã thêm thiết bị")}
  function addJob(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const item:Job={id:Math.max(...jobs.map(x=>x.id))+1,equipmentId:Number(f.get("equipment")),title:String(f.get("title")),due:String(f.get("due")),assignee:String(f.get("assignee")),status:"Scheduled",checklist:String(f.get("checklist")).split("\n").filter(Boolean).map(label=>({label,done:false})),faults:"",parts:""};setJobs([item,...jobs]);setCreateJob(false);setToast("Đã lên lịch bảo trì")}
  function saveJob(next:Job){setJobs(jobs.map(j=>j.id===next.id?next:j));setSelected(next)}
  function upload(file:File|undefined,kind:"beforePhoto"|"afterPhoto"){if(!file||!selected)return;const reader=new FileReader();reader.onload=()=>saveJob({...selected,[kind]:String(reader.result)});reader.readAsDataURL(file)}
  function generateReport(){if(!selected)return;const eq=equipment.find(e=>e.id===selected.equipmentId);const completed=selected.checklist.filter(c=>c.done).length;const report=`BÁO CÁO BẢO TRÌ\n\nThiết bị: ${eq?.name} (${eq?.code})\nCông việc: ${selected.title}\nKỹ thuật viên: ${selected.assignee}\nChecklist: ${completed}/${selected.checklist.length} hạng mục hoàn thành\nLỗi phát hiện: ${selected.faults||"Không ghi nhận"}\nLinh kiện thay thế: ${selected.parts||"Không có"}\n\nKết luận: ${completed===selected.checklist.length?"Đã hoàn tất toàn bộ hạng mục theo kế hoạch.":"Công việc chưa hoàn tất, cần tiếp tục các hạng mục còn lại."}`;saveJob({...selected,report});setToast("Đã tạo báo cáo")}
  if(!ready)return <div className="loader"><span/><span/><span/></div>;
  const nav=[{id:"dashboard",label:"Tổng quan",icon:Engine},{id:"schedule",label:"Lịch bảo trì",icon:CalendarBlank},{id:"equipment",label:"Thiết bị",icon:Toolbox},{id:"reports",label:"Báo cáo",icon:ClipboardText}];
  return <div className="shell"><aside><div className="brand"><span><Wrench size={22} weight="bold"/></span><div>Upkeep<small>Maintenance OS</small></div></div><nav>{nav.map(n=><button className={active===n.id?"active":""} key={n.id} onClick={()=>setActive(n.id)}><n.icon size={20}/>{n.label}</button>)}</nav><div className="safety"><WarningCircle size={21}/><p><strong>An toàn trước tiên</strong>Áp dụng LOTO và PPE theo quy trình.</p></div></aside><main><header><div><p>VDGS OPERATIONS</p><h1>{nav.find(n=>n.id===active)?.label}</h1></div><button className="outline" onClick={()=>setCreateJob(true)}><Plus size={18}/>Lên lịch</button></header>
  {active==="dashboard"&&<Dashboard stats={stats} jobs={jobs} equipment={equipment} open={setSelected}/>} 
  {active==="schedule"&&<Schedule jobs={jobs} equipment={equipment} open={setSelected} create={()=>setCreateJob(true)}/>} 
  {active==="equipment"&&<EquipmentView equipment={equipment} create={()=>setCreateEquipment(true)}/>} 
  {active==="reports"&&<Reports jobs={jobs} equipment={equipment} open={setSelected}/>} 
  <footer>Đây là app Demo được thực hiện bởi Phạm Đoàn Thiện Phong</footer></main>
  {selected&&<JobDrawer job={selected} equipment={equipment.find(e=>e.id===selected.equipmentId)} close={()=>setSelected(null)} save={saveJob} upload={upload} generate={generateReport}/>} 
  {createEquipment&&<Modal title="Thêm thiết bị" close={()=>setCreateEquipment(false)}><form className="form" onSubmit={addEquipment}><label>Tên thiết bị<input name="name" required/></label><label>Mã thiết bị<input name="code" required/></label><label>Vị trí<input name="location" required/></label><label>Loại<select name="type"><option>Electrical</option><option>Generator</option><option>HVAC</option><option>Pump</option><option>Other</option></select></label><label>Chu kỳ (ngày)<input name="interval" type="number" min="1" defaultValue="30" required/></label><label>Lần gần nhất<input name="lastService" type="date" required/></label><label className="full">Lần tiếp theo<input name="nextService" type="date" required/></label><div className="actions full"><button type="button" className="ghost" onClick={()=>setCreateEquipment(false)}>Hủy</button><button className="solid">Lưu thiết bị</button></div></form></Modal>}
  {createJob&&<Modal title="Lên lịch bảo trì" close={()=>setCreateJob(false)}><form className="form" onSubmit={addJob}><label className="full">Công việc<input name="title" required/></label><label>Thiết bị<select name="equipment">{equipment.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select></label><label>Ngày thực hiện<input name="due" type="date" required/></label><label className="full">Kỹ thuật viên<input name="assignee" required/></label><label className="full">Checklist, mỗi dòng một hạng mục<textarea name="checklist" defaultValue={"Kiểm tra an toàn\nVệ sinh thiết bị\nChạy thử và ghi thông số"} required/></label><div className="actions full"><button type="button" className="ghost" onClick={()=>setCreateJob(false)}>Hủy</button><button className="solid">Tạo lịch</button></div></form></Modal>}
  {toast&&<div className="toast"><CheckCircle size={19} weight="fill"/>{toast}</div>}</div>
}

function Dashboard({stats,jobs,equipment,open}:{stats:Record<string,number>;jobs:Job[];equipment:Equipment[];open:(j:Job)=>void}){return <><section className="hero"><div><p className="eyebrow">MAINTENANCE CONTROL</p><h2>Thiết bị khỏe.<br/>Vận hành liền mạch.</h2><p>Theo dõi công việc đến hạn, checklist và lỗi phát hiện trong cùng một nhịp vận hành.</p></div><div className="hero-visual"><div className="gauge"><span>{Math.round(equipment.filter(e=>e.health==="Good").length/equipment.length*100)}%</span><small>sức khỏe hệ thống</small></div><div className="barset">{equipment.map(e=><i key={e.id} style={{height:e.health==="Good"?"78%":e.health==="Attention"?"51%":"29%"}}/>)}</div></div></section><section className="metrics"><Metric label="Sắp đến hạn" value={stats.due} icon={<ClockCountdown/>}/><Metric label="Đang thực hiện" value={stats.progress} icon={<Wrench/>}/><Metric label="Đã hoàn thành" value={stats.done} icon={<CheckCircle/>}/><Metric label="Quá hạn" value={stats.overdue} icon={<WarningCircle/>} alert/></section><section className="content-grid"><div className="panel"><div className="panel-title"><h3>Công việc ưu tiên</h3><span>14 ngày tới</span></div>{jobs.filter(j=>j.status!=="Completed").slice(0,4).map(j=><JobRow key={j.id} job={j} equipment={equipment.find(e=>e.id===j.equipmentId)} open={()=>open(j)}/>)}</div><div className="panel health"><div className="panel-title"><h3>Cần chú ý</h3><span>{equipment.filter(e=>e.health!=="Good").length} thiết bị</span></div>{equipment.filter(e=>e.health!=="Good").map(e=><div className="health-row" key={e.id}><span className={e.health.toLowerCase()}><Engine size={20}/></span><div><strong>{e.name}</strong><small>{e.location}</small></div><b>{e.health}</b></div>)}</div></section></>}
function Metric({label,value,icon,alert=false}:{label:string;value:number;icon:React.ReactNode;alert?:boolean}){return <article className={alert?"metric alert":"metric"}><span>{icon}</span><b>{value}</b><small>{label}</small></article>}
function JobRow({job,equipment,open}:{job:Job;equipment?:Equipment;open:()=>void}){const done=job.checklist.filter(x=>x.done).length;return <button className="job-row" onClick={open}><div className={`datebox ${job.status.replace(" ","").toLowerCase()}`}><b>{new Date(job.due).getDate()}</b><span>TH{new Date(job.due).getMonth()+1}</span></div><div><strong>{job.title}</strong><small>{equipment?.code} / {job.assignee}</small></div><div className="completion"><b>{done}/{job.checklist.length}</b><small>checklist</small></div><CaretRight size={18}/></button>}
function Schedule({jobs,equipment,open,create}:{jobs:Job[];equipment:Equipment[];open:(j:Job)=>void;create:()=>void}){const [filter,setFilter]=useState("All");const shown=filter==="All"?jobs:jobs.filter(j=>j.status===filter);return <section className="panel page"><div className="toolbar"><div className="filters">{["All","Scheduled","In progress","Completed","Overdue"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><button className="solid" onClick={create}><Plus size={17}/>Thêm lịch</button></div>{shown.length?shown.map(j=><JobRow key={j.id} job={j} equipment={equipment.find(e=>e.id===j.equipmentId)} open={()=>open(j)}/>):<div className="empty"><CalendarBlank size={42}/><h3>Chưa có công việc</h3><p>Không có lịch bảo trì trong trạng thái này.</p></div>}</section>}
function EquipmentView({equipment,create}:{equipment:Equipment[];create:()=>void}){return <section className="page"><div className="section-head"><div><h2>Danh mục thiết bị</h2><p>Chu kỳ, vị trí và tình trạng bảo trì.</p></div><button className="solid" onClick={create}><Plus size={17}/>Thêm thiết bị</button></div><div className="equipment-grid">{equipment.map(e=><article className="equipment-card" key={e.id}><div className="equipment-icon"><Engine size={27}/></div><span className={`health-badge ${e.health.toLowerCase()}`}>{e.health}</span><p>{e.code}</p><h3>{e.name}</h3><small>{e.location}</small><dl><div><dt>Chu kỳ</dt><dd>{e.interval} ngày</dd></div><div><dt>Tiếp theo</dt><dd>{new Date(e.nextService).toLocaleDateString("vi-VN")}</dd></div></dl></article>)}</div></section>}
function Reports({jobs,equipment,open}:{jobs:Job[];equipment:Equipment[];open:(j:Job)=>void}){const completed=jobs.filter(j=>j.status==="Completed"||j.report);return <section className="page reports"><div className="section-head"><div><h2>Báo cáo bảo trì</h2><p>Tổng hợp công việc, lỗi và linh kiện đã thay.</p></div></div>{completed.length?completed.map(j=><button key={j.id} className="report-row" onClick={()=>open(j)}><ClipboardText size={24}/><div><strong>{j.title}</strong><small>{equipment.find(e=>e.id===j.equipmentId)?.name} / {j.assignee}</small></div><span>{j.report?"AI report":"Biên bản"}</span><CaretRight/></button>):<div className="empty"><ClipboardText size={42}/><h3>Chưa có báo cáo</h3><p>Hoàn thành một công việc để tạo báo cáo.</p></div>}</section>}
function JobDrawer({job,equipment,close,save,upload,generate}:{job:Job;equipment?:Equipment;close:()=>void;save:(j:Job)=>void;upload:(f:File|undefined,k:"beforePhoto"|"afterPhoto")=>void;generate:()=>void}){return <div className="drawer-backdrop" onMouseDown={close}><aside className="drawer" onMouseDown={e=>e.stopPropagation()}><div className="drawer-head"><div><span>WORK ORDER #{job.id}</span><h2>{job.title}</h2><p>{equipment?.name} / {equipment?.location}</p></div><button onClick={close}>×</button></div><div className="drawer-status"><label>Trạng thái<select value={job.status} onChange={e=>save({...job,status:e.target.value as JobStatus})}><option>Scheduled</option><option>In progress</option><option>Completed</option><option>Overdue</option></select></label><label>Ngày thực hiện<input type="date" value={job.due} onChange={e=>save({...job,due:e.target.value})}/></label></div><section><h3>Checklist công việc</h3><div className="checklist">{job.checklist.map((item,i)=><label key={`${item.label}-${i}`}><input type="checkbox" checked={item.done} onChange={()=>save({...job,checklist:job.checklist.map((x,n)=>n===i?{...x,done:!x.done}:x)})}/><span><Check size={15}/></span>{item.label}</label>)}</div></section><section className="notes"><label>Lỗi phát hiện<textarea value={job.faults} onChange={e=>save({...job,faults:e.target.value})} placeholder="Ghi lại triệu chứng và thông số bất thường..."/></label><label>Linh kiện đã thay<textarea value={job.parts} onChange={e=>save({...job,parts:e.target.value})} placeholder="Tên linh kiện, part number, số lượng..."/></label></section><section><h3>Ảnh hiện trường</h3><div className="photos"><PhotoBox title="Trước bảo trì" image={job.beforePhoto} onFile={f=>upload(f,"beforePhoto")}/><PhotoBox title="Sau bảo trì" image={job.afterPhoto} onFile={f=>upload(f,"afterPhoto")}/></div></section><button className="ai-button" onClick={generate}><Sparkle size={19} weight="fill"/>Tạo maintenance report</button>{job.report&&<pre className="report-text">{job.report}</pre>}</aside></div>}
function PhotoBox({title,image,onFile}:{title:string;image?:string;onFile:(f:File|undefined)=>void}){return <label className="photo-box">{image?<img src={image} alt={title}/>:<><Camera size={25}/><span>{title}</span></>}<input type="file" accept="image/*" onChange={e=>onFile(e.target.files?.[0])}/></label>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modal-backdrop" onMouseDown={close}><section className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><h2>{title}</h2><button onClick={close}>×</button></div>{children}</section></div>}
